"""Generate CSE-optimized hardcoded mean rate and short-period functions.

Stage B of the performance optimization plan.  Reads the symbolic expressions
from ``generated_coefficients.py``, converts complex w^m harmonics to real
cos/sin arithmetic, applies SymPy CSE, and emits a self-contained Python module
``hardcoded_rates.py`` with no SymPy dependency at runtime.

Usage:
    conda run -n astrodyn-core-env python docs/geqoe_averaged/geqoe_mean/generate_hardcoded.py
"""

from __future__ import annotations

import textwrap
import time
from pathlib import Path

import sympy as sp

# ── Symbols for code generation ──────────────────────────────────────────

q_sym = sp.Symbol("q", real=True, positive=True)
Q_sym = sp.Symbol("Q", real=True, positive=True)
omega_sym = sp.Symbol("omega", real=True)
s2, s3, s4, s5 = sp.symbols("s2 s3 s4 s5", real=True)

_SYMPIFY_LOCALS = {"q": q_sym, "Q": Q_sym, "I": sp.I}
_SCALE_MAP = {2: s2, 3: s3, 4: s4, 5: s5}
_VARIABLES = ("g", "Q", "Psi", "Omega", "M")


# ── Helpers ──────────────────────────────────────────────────────────────

def _load_mean_data() -> dict:
    """Load MEAN_DATA from generated_coefficients.py via AST."""
    import ast
    data_file = Path(__file__).resolve().parent / "generated_coefficients.py"
    tree = ast.parse(data_file.read_text())
    for node in tree.body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name)
                and node.targets[0].id == "MEAN_DATA"):
            return ast.literal_eval(node.value)
    raise RuntimeError("MEAN_DATA not found in generated_coefficients.py")


def _to_real_trig(coeffs: dict[str, str]) -> sp.Expr:
    """Convert {m_str: expr_str} Fourier sum to a real trigonometric expression.

    Each coefficient c_m(q,Q) may be real or pure imaginary (I*f).
    The real part of sum_m c_m * exp(i*m*omega) is:
        Re(c_m) * cos(m*omega) - Im(c_m) * sin(m*omega)
    """
    total = sp.Integer(0)
    for m_str, expr_str in coeffs.items():
        m = int(m_str)
        c = sp.sympify(expr_str, locals=_SYMPIFY_LOCALS)
        if c == 0:
            continue
        c_re = sp.re(c)
        c_im = sp.im(c)
        if m == 0:
            total += c_re
        else:
            total += c_re * sp.cos(m * omega_sym) - c_im * sp.sin(m * omega_sym)
    return total


def _build_mean_rate_expressions(mean_data: dict) -> dict[str, sp.Expr]:
    """Build the 5 combined mean rate expressions in real arithmetic.

    Returns {variable: expr} where expr is a function of (q, Q, omega, s2..s5).
    The caller multiplies by nu to get the physical rate.
    """
    rates = {v: sp.Integer(0) for v in _VARIABLES}
    for n_key, var_map in sorted(mean_data.items()):
        n = int(n_key)
        scale = _SCALE_MAP[n]
        for variable in _VARIABLES:
            coeffs = var_map.get(variable, {})
            trig_expr = _to_real_trig(coeffs)
            if trig_expr != 0:
                rates[variable] += scale * trig_expr
    return rates


# ── Code emission ────────────────────────────────────────────────────────

def _emit_expr(expr: sp.Expr) -> str:
    """Convert a SymPy expression to a Python string using ``import math``."""
    from sympy.printing.pycode import PythonCodePrinter

    class _Printer(PythonCodePrinter):
        def _print_Symbol(self, expr):
            return expr.name

    return _Printer().doprint(expr)


def generate_mean_rates_module(mean_data: dict) -> str:
    """Generate the full hardcoded_rates.py source code."""
    print("  Building combined real-trig expressions...")
    t0 = time.time()
    rates = _build_mean_rate_expressions(mean_data)
    print(f"    done in {time.time() - t0:.1f}s")

    # Collect all non-zero rate expressions for CSE
    exprs = []
    labels = []
    for variable in _VARIABLES:
        e = sp.cancel(sp.expand(rates[variable]))
        exprs.append(e)
        labels.append(f"d{variable}" if variable != "Q" else "dQ_rate")

    print(f"  Running CSE on {len(exprs)} expressions...")
    t0 = time.time()
    replacements, reduced = sp.cse(exprs, optimizations="basic")
    print(f"    CSE found {len(replacements)} shared subexpressions in {time.time() - t0:.1f}s")

    # ── Emit Python module ──
    lines = [
        '"""CSE-optimized mean rate evaluator (auto-generated, do not edit).',
        '',
        'Generated by generate_hardcoded.py.  Pure Python arithmetic — no SymPy',
        'dependency at runtime.  Provides mean_rates_cse() returning dimensionless',
        'rates (g_dot, Q_dot, Psi_dot, Omega_dot, M_dot) / nu.',
        '"""',
        '',
        'import math',
        '',
        '',
        'def mean_rates_cse(q: float, Q: float, omega: float,',
        '                   s2: float, s3: float, s4: float, s5: float',
        '                   ) -> tuple[float, float, float, float, float]:',
        '    """Compute dimensionless mean rates via CSE-optimized arithmetic.',
        '',
        '    Parameters',
        '    ----------',
        '    q : eccentricity parameter g/(1+beta)',
        '    Q : inclination parameter ||(q1,q2)||',
        '    omega : argument of perigee (Psi - Omega)',
        '    s2..s5 : scale factors Jn*(Re/a)^n for zonal degrees 2-5',
        '',
        '    Returns',
        '    -------',
        '    (g_dot, Q_dot, Psi_dot, Omega_dot, M_dot) / nu',
        '    """',
    ]

    # Emit CSE intermediates
    for sym, expr in replacements:
        lines.append(f"    {sym.name} = {_emit_expr(expr)}")

    lines.append("")
    # Emit final rate expressions
    for label, expr in zip(labels, reduced):
        lines.append(f"    {label} = {_emit_expr(expr)}")

    lines.append("")
    lines.append("    return dg, dQ_rate, dPsi, dOmega, dM")
    lines.append("")

    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────────────────────

def main():
    print("Stage B: Generating CSE-optimized hardcoded mean rates...")
    mean_data = _load_mean_data()

    # Count non-zero terms
    nz = sum(
        1 for n_data in mean_data.values()
        for v_data in n_data.values()
        for expr_str in v_data.values()
        if expr_str != "0" and expr_str != "'0'"
    )
    print(f"  Non-zero mean coefficients: {nz}")

    source = generate_mean_rates_module(mean_data)

    out_path = Path(__file__).resolve().parent / "hardcoded_rates.py"
    out_path.write_text(source)
    print(f"  Wrote {out_path} ({len(source)} bytes)")

    # Quick smoke test
    print("  Smoke test...")
    ns = {}
    exec(compile(source, str(out_path), "exec"), ns)
    fn = ns["mean_rates_cse"]
    result = fn(0.01, 0.1, 0.5, 1e-3, 1e-6, 1e-9, 1e-12)
    print(f"    mean_rates_cse(0.01, 0.1, 0.5, ...) = {result}")
    print("  Done.")


if __name__ == "__main__":
    main()
